version: '3.8'
services:
  api:
    build: ./
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
  worker:
    build: ./
    command: celery -A workers.tasks worker --loglevel=info
    depends_on:
      - redis
  redis:
    image: redis:alpine
